[build]
builder = "nixpacks"
buildCommand = "npm run install-all"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[nixpacks]
node-version = "18" 