[build]
builder = "nixpacks"
buildCommand = "npm install --no-package-lock && cd server && npm install --no-package-lock"

[deploy]
startCommand = "cd server && node server.js"
healthcheckPath = "/health"
healthcheckTimeout = 300

[nixpacks]
node-version = "18"
npm-version = "10.2.4" 